name: Run Tests

on: push

jobs:
  create-release:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout repository from GitHub
        uses: actions/checkout@v2.3.1
      - name: Setup npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      # npm cache folder is in ~/, not within the working directory
      - name: Cache npm directory
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Build library for examples
        run: npm run build -w library
      - name: Run tests
        run: npm run test
